services:
  - type: web
    name: echo-mcp-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    autoDeploy: false
    port: 8000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"